// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfC0EgRqJo8fAM4xY7VexEHezVBtQt9YM',
    appId: '1:288535839111:web:e19c8cf707ad8c03b51322',
    messagingSenderId: '288535839111',
    projectId: 'fir-test-1ed02',
    authDomain: 'fir-test-1ed02.firebaseapp.com',
    storageBucket: 'fir-test-1ed02.appspot.com',
    measurementId: 'G-KS7XQYR1JQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCznALfOMJyOFFvpjtXTJxC9X8v0k2o750',
    appId: '1:288535839111:android:bedf4f39ec1810efb51322',
    messagingSenderId: '288535839111',
    projectId: 'fir-test-1ed02',
    storageBucket: 'fir-test-1ed02.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcfluv3mY6E5fNYKmZJNzmtv_XsCEv664',
    appId: '1:288535839111:ios:9f6fcd77f2b6c52bb51322',
    messagingSenderId: '288535839111',
    projectId: 'fir-test-1ed02',
    storageBucket: 'fir-test-1ed02.appspot.com',
    iosClientId: '288535839111-j8tu8ch6goll8k3ott8bl6bd0tdc2hv7.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecosoftvmsgate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcfluv3mY6E5fNYKmZJNzmtv_XsCEv664',
    appId: '1:288535839111:ios:b7d2899b0ae7e015b51322',
    messagingSenderId: '288535839111',
    projectId: 'fir-test-1ed02',
    storageBucket: 'fir-test-1ed02.appspot.com',
    iosClientId: '288535839111-ccbqtqnf2mq7nmgg3q2o9hkpf659u5kc.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecosoftvmsgate.RunnerTests',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfC0EgRqJo8fAM4xY7VexEHezVBtQt9YM',
    appId: '1:288535839111:web:fc9e34aeac9217bab51322',
    messagingSenderId: '288535839111',
    projectId: 'fir-test-1ed02',
    authDomain: 'fir-test-1ed02.firebaseapp.com',
    storageBucket: 'fir-test-1ed02.appspot.com',
    measurementId: 'G-E0NRDYL94L',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyBfC0EgRqJo8fAM4xY7VexEHezVBtQt9YM',
    appId: '1:288535839111:web:fe8ec2e5b4a0ddfcb51322',
    messagingSenderId: '288535839111',
    projectId: 'fir-test-1ed02',
    authDomain: 'fir-test-1ed02.firebaseapp.com',
    storageBucket: 'fir-test-1ed02.appspot.com',
    measurementId: 'G-NGP1SG4XWD',
  );
}
